### ISSUE TITLE
Remove redundant lines

### ISSUE THREAD

**Issue by luzpaz** [orbitcowboy/codespell_dictionary#1]
```
achive->achieve
achive->achieve, archive
achive->achieve, archive,
achived->achieved
achived->achieved, archived
achived->achieved, archived,
achived->archived
```

**Comment by orbitcowboy** [comment]
Fixed with https://github.com/orbitcowboy/codespell_dictionary/commit/73a708cbddbf5977479a21ed43d91fa42d908f2e

**Comment by luzpaz** [comment]
There is way more than this. This was just a template example of what to look for.
