### ISSUE TITLE
Set license to GNU General Public License v2.0

### ISSUE THREAD

**Issue by orbitcowboy** [orbitcowboy/codespell_dictionary#10]
I intend to set the license to **GNU General Public License v2.0** for this project. @luzpaz  please let me know if you agree with that.

**Comment by luzpaz** [comment]
sure, why not v3 ?

**Comment by orbitcowboy** [comment]
I would like to have the same license as codespell. Ok?

**Comment by orbitcowboy** [comment]
Fixed by https://github.com/orbitcowboy/codespell_dictionary/commit/29fc630dfceaea7c25166f611189c0229dac5911
