### ISSUE TITLE
what is used to sort the dictionary?

### ISSUE THREAD

**Issue by luzpaz** [orbitcowboy/codespell_dictionary#12]
what is the command that is preferred?

**Comment by orbitcowboy** [comment]
There is a bash script `sortDictionariesAndCleanup.sh`.
Use it like this on Linux:

`$ bash sortDictionariesAndCleanup.sh`

**Comment by luzpaz** [comment]
> There is a bash script `sortDictionariesAndCleanup.sh`.
> Use it like this on Linux:
> 
> `$ bash sortDictionariesAndCleanup.sh`

When I use this, the modifications to the file are massive!  
https://github.com/luzpaz/codespell_dictionary/tree/sorted

**Comment by orbitcowboy** [comment]
Interesting! May i ask what Linux OS you are using. The script works as expected on Ubuntu 19.10.

**Comment by luzpaz** [comment]
```
Description:	Manjaro Linux
Release:	18.1.0
Codename:	Juhraya
```

**Comment by orbitcowboy** [comment]
I made some updates on the script. Could you please retry?

**Comment by orbitcowboy** [comment]
@luzpaz Does the script now sort the dictionary file as expected on your OS?

**Comment by luzpaz** [comment]
yes...thank you and well done :)
