### ISSUE TITLE
Remove blatantly incorrect entries

### ISSUE THREAD

**Issue by luzpaz** [orbitcowboy/codespell_dictionary#3]
these are legit words e.g.    
```
graphic->graphical
conform->confirm
forth->fourth
modulus->modulo
assemble->assembly
cascade->casade
```

etc...

**Comment by orbitcowboy** [comment]
Thanks for your contribution, i will leave this open.

**Comment by luzpaz** [comment]
The PR that fixed these, #5 was reverted e8f2ecd3c8602 right after it was merged...why ?

**Comment by orbitcowboy** [comment]
This happened by accident. I'll integrate your changes again. Thank you for letting me know :-)

**Comment by orbitcowboy** [comment]
Done with https://github.com/orbitcowboy/codespell_dictionary/commit/ae35047a9806c929df188e3f4f91701aefd21f75
