### ISSUE TITLE
Remove duplicate typo->correction

### ISSUE THREAD

**Issue by luzpaz** [orbitcowboy/codespell_dictionary#4]
Create a script that searches for these issues and corrects them. There are many in the dictionary. Here's an example:  
`australia->australia`

**Comment by orbitcowboy** [comment]
Thanks! Fixed with https://github.com/orbitcowboy/codespell_dictionary/commit/a8eca434c1ba7712945a8fb7f1b5a70632113ba3

**Comment by luzpaz** [comment]
There is way more than this. This was just a template example of what to look for.
